### PR TITLE
ensure that child grunt processes have color mode enabled

### PR DESCRIPTION
**Pull request by mrfelton**
quick fix for #49

### CODE REVIEW

**Comment by shama** [comment]
Wouldn't this enable colors all the time? Even if the user has set `--no-color`?

**Comment by mrfelton** [comment]
Yep, thats why I called it a quick fix ;)

**Comment by shama** [comment]
We're not in a hurry to fix though ;)

**Comment by mrfelton** [comment]
thats fine - just thought you could use this as a starting point for when you get the time to incorporate a fix.

**Comment by shama** [comment]
It's not an issue I'm running into so it's not likely going to be fixed by me. I'd happily accept a patch that actually fixes the issue though. Thanks!

**Pull request closed without merging**
